"""Write the example tables of docs/internal/progress/examples.tex.

Every sentence is read from the collated data or a saved infilling run by its
article id and sentence index, never typed by hand, and escaped for LaTeX.

Usage:
    python -m analysis.report_examples --data ../datasets/collated/train.jsonl \\
        --pre ../datasets/archive/collated/train.pre_keepfix.jsonl --runs outputs/jl/runs \\
        --out ../../docs/internal/progress/examples.tex
"""

import argparse
import json
from pathlib import Path

from classifier.inputs import read_jsonl

SPECIAL = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
           "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def tex(text):
    out = "".join(SPECIAL.get(ch, ch) for ch in text.strip())
    return out.replace("''", "\\textquotesingle\\textquotesingle{}").replace("[", "{[}").replace("]", "{]}")


def case(title, rows, note):
    """One example: a heading, label and text rows, and a note."""
    body = "\n".join(f"\\textsf{{{label}}} & {text} \\\\" for label, text in rows)
    return (f"\\begin{{table}}[H]\n\\footnotesize\n\\begin{{tabular}}{{@{{}}p{{0.17\\linewidth}}p{{0.79\\linewidth}}@{{}}}}\n"
            f"\\toprule\n\\multicolumn{{2}}{{@{{}}l}}{{\\textbf{{{title}}}}} \\\\\n\\midrule\n{body}\n\\midrule\n"
            f"\\multicolumn{{2}}{{@{{}}p{{0.97\\linewidth}}@{{}}}}{{{note}}} \\\\\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data", required=True)
    parser.add_argument("--pre", required=True)
    parser.add_argument("--runs", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    data_ids = {"train-000003", "train-000004", "train-000012", "train-000159", "train-000780", "train-000862",
                "train-042079", "train-057216", "train-002320"}
    runs_dir = Path(args.runs)
    runs = {k: {r["id"]: r for r in read_jsonl(runs_dir / d / "results.jsonl")}
            for k, d in (("oracle", "fix-oracle"), ("noev", "fix-oracle-noev"), ("predicted", "fix-predicted"),
                         ("first", "infill-full-predicted"))}
    infill_ids = {"train-000184", "train-001621", "train-002079", "train-001500", "train-000076", "train-000455",
                  "train-000101", "train-000000"}
    rec = {r["id"]: r for r in read_jsonl(args.data) if r["id"] in data_ids | infill_ids}
    pre = {r["id"]: r for r in read_jsonl(args.pre) if r["id"] in data_ids}

    def src(aid, i):
        return tex(rec[aid]["source_sentences"][i])

    def gold(aid, i):
        return tex(rec[aid]["target_sentences"][rec[aid]["labels"][i]["target_idx"]]["text"])

    def target(aid, j):
        return tex(rec[aid]["target_sentences"][j]["text"])

    def lab(aid, i):
        entry = rec[aid]["labels"][i]
        return f"\\{entry['label'].lower()}{{}} (similarity {entry['similarity']:.2f})"

    def out(run, aid, i):
        return tex(runs[run][aid]["output"][i])

    def masked(run, aid, i):
        edit = next(e for e in runs[run][aid]["edits"] if e["sentence"] == i)
        return ", ".join("``" + tex(m) + "''" for m in edit["masked"])

    blocks = ["% generated by analysis/report_examples.py, do not edit by hand\n"]
    blocks.append("\\subsection{Data}\n")
    blocks.append(case(
        "D1. An edit whose new numbers the evidence does not contain (train-000004, sentence 2)",
        [("Source", src("train-000004", 2)), ("Gold rewrite", gold("train-000004", 2)),
         ("Label", lab("train-000004", 2))],
        "The revision updated the career totals, but no snippet of the article's evidence, cut or uncut, contains "
        "327 or 38. No system can derive this rewrite from its input, yet the label asks for it. Only 16.9\\% of "
        "edited sentences with new words have those words in the input."))
    blocks.append(case(
        "D2. A source sentence paired with an unrelated target fragment (train-000004, sentence 4)",
        [("Source", src("train-000004", 4)), ("Paired target", target("train-000004", rec["train-000004"]["labels"][4]["target_idx"])),
         ("Label", lab("train-000004", 4))],
        "The target sentence is a fragment of a linearized results table. It shares the words FC, Lokomotive and "
        "Leipzig with the source, which puts the similarity at 0.53, above the 0.35 floor. The aligner pairs the two "
        "and the diff marks ``was renamed to VfB Leipzig'' stale."))
    blocks.append(case(
        "D3. Two source sentences merged into one target sentence (train-000159, sentences 2 and 3)",
        [("Source 2", src("train-000159", 2)), ("Source 3", src("train-000159", 3)),
         ("Target", target("train-000159", rec["train-000159"]["labels"][2]["target_idx"])),
         ("Labels", f"source 2: {lab('train-000159', 2)}; source 3: \\drop{{}}, its best similarity 0.60 is to the same target")],
        "The revision joined the two sentences with a semicolon. Each target sentence can pair with one source "
        "sentence, so source 2 takes the merged sentence first (0.67) and source 3, whose content survives "
        "unchanged, becomes \\drop{}."))
    blocks.append(case(
        "D4. A sentence split inside a quoted title (train-000780, sentence 3)",
        [("Source 3", src("train-000780", 3)), ("Source 4", src("train-000780", 4)), ("Label of source 3", "\\drop{}")],
        "spaCy split the sentence at the exclamation mark inside the column's name. The second half pairs with the "
        "rewritten target, and the first half becomes \\drop{}. The hand review found 6 such non-sentences among "
        "117 flagged rows, including a lone full stop, ``(image)'' and ``\\_\\_TOC\\_\\_''."))
    blocks.append(case(
        "D5. The KEEP fix turns a reformatted date into an edit (train-000003, sentence 0)",
        [("Source", src("train-000003", 0)), ("Gold rewrite", gold("train-000003", 0)),
         ("Label", f"before the fix \\{pre['train-000003']['labels'][0]['label'].lower()}{{}}, after the fix {lab('train-000003', 0)}")],
        "The date only changed format, but 26 and 1980 contain digits, so the \\keep{} fix labels the "
        "sentence \\edit{} and marks the date stale. A diacritic added to Bhagavad Gita in train-000012 becomes an "
        "\\edit{} the same way. The fix exists for cases like D6."))
    blocks.append(case(
        "D6. A real update the fix catches (train-057216, sentence 0, from the hand review)",
        [("Source", src("train-057216", 0)), ("Gold rewrite", gold("train-057216", 0)),
         ("Label", f"before the fix \\{pre['train-057216']['labels'][0]['label'].lower()}{{}}, after the fix {lab('train-057216', 0)}")],
        "A one-word club change keeps the similarity above 0.95, so the first build labelled the sentence "
        "\\keep{}. The reviewer marked it \\edit{}, as for 8 of the 24 errors found, and the fix now agrees."))
    blocks.append(case(
        "D7. A rephrasing labelled as an edit (train-042079, sentence 0, from the hand review)",
        [("Source", src("train-042079", 0)), ("Gold rewrite", gold("train-042079", 0)), ("Label", lab("train-042079", 0))],
        "The revision dropped the state name without changing any fact. The reviewer judged the label wrong and "
        "the sentence \\keep{}, as for 13 of the 24 errors found. The staleness head still learns to treat "
        "``Illinois'' as stale."))
    blocks.append(case(
        "D8. The evidence that supports an update cut by the token budget (train-000862, sentence 5)",
        [("Source", src("train-000862", 5)), ("Gold rewrite", gold("train-000862", 5)),
         ("Evidence", "The snippet titled ``Biswanath Somadder'' kept 0 of its 118 characters after the cut.")],
        "The snippets are ordered by how many mentions they share with the old article. The snippet about the new "
        "Chief Justice shares none, so it comes last and the 600-token budget empties it. The input then lacks the "
        "name and the date the update needs."))
    blocks.append(case(
        "D9. A stylistic change marked stale (train-002320, sentence 0)",
        [("Source", src("train-002320", 0)), ("Gold rewrite", target("train-002320", 1)),
         ("Stale spans", ", ".join("``" + tex(rec["train-002320"]["source_sentences"][0][a:b]) + "''"
                                   for a, b in rec["train-002320"]["labels"][0]["stale_spans"]))],
        "The diff marks both the new area and the replacement of the park's name by ``It''. Only the first is a "
        "fact the evidence states. The second is a style choice of the revision."))

    blocks.append("\\subsection{Infilling}\n")
    blocks.append(case(
        "I1. The evidence supplies the new club (train-000184, sentence 0)",
        [("Source", src("train-000184", 0)), ("Oracle masks", masked("oracle", "train-000184", 0)),
         ("Gold rewrite", gold("train-000184", 0)), ("Oracle output", out("oracle", "train-000184", 0)),
         ("No evidence", out("noev", "train-000184", 0)), ("Predicted masks", out("predicted", "train-000184", 0))],
        "With the evidence, the model writes the right club. Without it, the model writes a plausible but wrong "
        "club and league. The entity measures count ``Alessandria'' as fabricated, because the evidence names the "
        "club only inside a linearized table, where spaCy finds no entities. Counting a mention as supported when "
        "its text occurs in the evidence lowers the fabricated share of the oracle run from 14.4\\% to 10.6\\%, "
        "of the run without evidence from 22.9\\% to 19.9\\%, and of the predicted run from 24.7\\% to 18.7\\%."))
    blocks.append(case(
        "I2. A transfer the model reads from the evidence (train-001621, sentence 0)",
        [("Source", src("train-001621", 0)), ("Oracle masks", masked("oracle", "train-001621", 0)),
         ("Gold rewrite", gold("train-001621", 0)), ("Oracle output", out("oracle", "train-001621", 0)),
         ("No evidence", out("noev", "train-001621", 0))],
        "The oracle output takes RCD Mallorca from the evidence but keeps ``on loan from Cádiz CF'', because the "
        "mask set covers it and the chosen candidate refilled it. Without the evidence, the model invents a "
        "different club and a different loan."))
    blocks.append(case(
        "I3. A number the model cannot recover (train-002079, sentence 1)",
        [("Source", src("train-002079", 1)), ("Oracle masks", masked("oracle", "train-002079", 1)),
         ("Gold rewrite", gold("train-002079", 1)), ("Oracle output", out("oracle", "train-002079", 1)),
         ("Predicted masks", out("predicted", "train-002079", 1))],
        "The word diff splits 7,541 at the comma, so only 541 is stale. The model fills it with a round 000, adds "
        "``Cree'', and writes 2006 for the census year. The predicted masks cover the number and the census, and "
        "the output breaks off mid-sentence."))
    blocks.append(case(
        "I4. Oracle masks too small to express the rewrite (train-000076, sentence 0)",
        [("Source", src("train-000076", 0)), ("Oracle masks", masked("oracle", "train-000076", 0)),
         ("Gold rewrite", gold("train-000076", 0)), ("Oracle output", out("oracle", "train-000076", 0)),
         ("Predicted masks", out("predicted", "train-000076", 0))],
        "The diff marks only ``in'' and the comma, the anchors of two insertions. Lengths up to the masked length "
        "plus two cannot hold ``the San José province of'', so the oracle run returns the source unchanged. The "
        "predicted mask covers ``Aserrí Canton, Costa Rica'', and the output names the province but drops the "
        "canton."))
    blocks.append(case(
        "I5. Predicted masks rewrite correct text (train-001500, sentence 2)",
        [("Source", src("train-001500", 2)), ("Gold rewrite", gold("train-001500", 2)),
         ("Oracle output", out("oracle", "train-001500", 2)), ("Predicted masks", out("predicted", "train-001500", 2))],
        "The update only renames the station. The predicted masks also cover ``is'' and ``Pendleton'', and the "
        "model replaces the correct Pendleton with Richland."))
    blocks.append(case(
        "I6. A typo repaired, and a new error introduced (train-000455, sentence 2)",
        [("Source", src("train-000455", 2)), ("Gold rewrite", gold("train-000455", 2)),
         ("Oracle output", out("oracle", "train-000455", 2)), ("No evidence", out("noev", "train-000455", 2)),
         ("Predicted masks", out("predicted", "train-000455", 2))],
        "The oracle output fixes the misspelled name. The predicted masks also cover ``name for US war on ISIS'', "
        "and the model turns the war on ISIS into a mission in Afghanistan."))
    blocks.append(case(
        "I7. A list item updated from the evidence (train-000101, sentence 4)",
        [("Source", src("train-000101", 4)), ("Gold rewrite", gold("train-000101", 4)),
         ("Oracle output", out("oracle", "train-000101", 4)), ("No evidence", out("noev", "train-000101", 4)),
         ("Predicted masks", out("predicted", "train-000101", 4))],
        "With the evidence, the model writes the new film and year, with a spurious ``both''. Without it, the model "
        "invents a different title and year range."))
    first = runs["first"]["train-000000"]
    j = next(e["sentence"] for e in first["edits"] if "charactersanzi" in first["output"][e["sentence"]] or
             any("charactersanzi" in c["text"] for d in e["decisions"] for c in d["candidates"]))
    edit = next(e for e in first["edits"] if e["sentence"] == j)
    cand = next(c["text"] for d in edit["decisions"] for c in d["candidates"] if "charactersanzi" in c["text"])
    blocks.append(case(
        f"I8. A mask that cut a word in half, first run (train-000000, sentence {j})",
        [("Source", tex(rec["train-000000"]["source_sentences"][j])),
         ("Masked spans", ", ".join("``" + tex(m) + "''" for m in edit["masked"])),
         ("A candidate", tex(cand))],
        "The token mask covered ``h'' of ``hanzi'' but not the rest of the word. The length-zero candidate then "
        "joined ``characters'' and ``anzi''. Widening masks to whole words removes this failure."))
    Path(args.out).write_text("\n".join(blocks))
    print(f"wrote {args.out}: {sum(b.count('begin{table}') for b in blocks)} examples")


if __name__ == "__main__":
    main()
